/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as BaseRouteImport } from './routes/_base/route'
import { Route as AuthRouteImport } from './routes/_auth/route'
import { Route as RouteImport } from './routes/*/route'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup/route'
import { Route as AuthLoginRouteImport } from './routes/_auth/login/route'

// Create Virtual Routes

const BaseIndexLazyImport = createFileRoute('/_base/')()
const Base500LazyImport = createFileRoute('/_base/500')()
const Base404LazyImport = createFileRoute('/_base/404')()
const Base403LazyImport = createFileRoute('/_base/403')()
const BaseDashboardRouteLazyImport = createFileRoute('/_base/dashboard')()
const AuthSsoRouteLazyImport = createFileRoute('/_auth/sso')()
const AuthForgotPasswordRouteLazyImport = createFileRoute(
  '/_auth/forgot-password',
)()

// Create/Update Routes

const BaseRouteRoute = BaseRouteImport.update({
  id: '/_base',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/_base/route.lazy').then((d) => d.Route))

const AuthRouteRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/_auth/route.lazy').then((d) => d.Route))

const RouteRoute = RouteImport.update({
  path: '/*',
  getParentRoute: () => rootRoute,
} as any)

const BaseIndexLazyRoute = BaseIndexLazyImport.update({
  path: '/',
  getParentRoute: () => BaseRouteRoute,
} as any).lazy(() => import('./routes/_base/index.lazy').then((d) => d.Route))

const Base500LazyRoute = Base500LazyImport.update({
  path: '/500',
  getParentRoute: () => BaseRouteRoute,
} as any).lazy(() => import('./routes/_base/500.lazy').then((d) => d.Route))

const Base404LazyRoute = Base404LazyImport.update({
  path: '/404',
  getParentRoute: () => BaseRouteRoute,
} as any).lazy(() => import('./routes/_base/404.lazy').then((d) => d.Route))

const Base403LazyRoute = Base403LazyImport.update({
  path: '/403',
  getParentRoute: () => BaseRouteRoute,
} as any).lazy(() => import('./routes/_base/403.lazy').then((d) => d.Route))

const BaseDashboardRouteLazyRoute = BaseDashboardRouteLazyImport.update({
  path: '/dashboard',
  getParentRoute: () => BaseRouteRoute,
} as any).lazy(() =>
  import('./routes/_base/dashboard/route.lazy').then((d) => d.Route),
)

const AuthSsoRouteLazyRoute = AuthSsoRouteLazyImport.update({
  path: '/sso',
  getParentRoute: () => AuthRouteRoute,
} as any).lazy(() =>
  import('./routes/_auth/sso/route.lazy').then((d) => d.Route),
)

const AuthForgotPasswordRouteLazyRoute =
  AuthForgotPasswordRouteLazyImport.update({
    path: '/forgot-password',
    getParentRoute: () => AuthRouteRoute,
  } as any).lazy(() =>
    import('./routes/_auth/forgot-password/route.lazy').then((d) => d.Route),
  )

const AuthSignupRouteRoute = AuthSignupRouteImport.update({
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any).lazy(() =>
  import('./routes/_auth/signup/route.lazy').then((d) => d.Route),
)

const AuthLoginRouteRoute = AuthLoginRouteImport.update({
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any).lazy(() =>
  import('./routes/_auth/login/route.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/*': {
      preLoaderRoute: typeof RouteImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRoute
    }
    '/_base': {
      preLoaderRoute: typeof BaseRouteImport
      parentRoute: typeof rootRoute
    }
    '/_auth/login': {
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/signup': {
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/forgot-password': {
      preLoaderRoute: typeof AuthForgotPasswordRouteLazyImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/sso': {
      preLoaderRoute: typeof AuthSsoRouteLazyImport
      parentRoute: typeof AuthRouteImport
    }
    '/_base/dashboard': {
      preLoaderRoute: typeof BaseDashboardRouteLazyImport
      parentRoute: typeof BaseRouteImport
    }
    '/_base/403': {
      preLoaderRoute: typeof Base403LazyImport
      parentRoute: typeof BaseRouteImport
    }
    '/_base/404': {
      preLoaderRoute: typeof Base404LazyImport
      parentRoute: typeof BaseRouteImport
    }
    '/_base/500': {
      preLoaderRoute: typeof Base500LazyImport
      parentRoute: typeof BaseRouteImport
    }
    '/_base/': {
      preLoaderRoute: typeof BaseIndexLazyImport
      parentRoute: typeof BaseRouteImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  RouteRoute,
  AuthRouteRoute.addChildren([
    AuthLoginRouteRoute,
    AuthSignupRouteRoute,
    AuthForgotPasswordRouteLazyRoute,
    AuthSsoRouteLazyRoute,
  ]),
  BaseRouteRoute.addChildren([
    BaseDashboardRouteLazyRoute,
    Base403LazyRoute,
    Base404LazyRoute,
    Base500LazyRoute,
    BaseIndexLazyRoute,
  ]),
])

/* prettier-ignore-end */
