name: front linter

on:
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - 'refs/heads/main'
    types: [opened, synchronize, reopened]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: install pnpm
        run: npm install -g pnpm
      - name: install dependencies
        run: pnpm install
      - name: type check
        run: pnpm type:check
      - name: cspell check
        run: pnpm cspell:check
      - name: ESLint
        run: pnpm eslint:check
      - name: Prettier
        run: pnpm prettier:check

  send-msg:
    needs: linter
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Send wecom message if linter failed
        if: ${{ needs.linter.result != 'success' }}
        uses: chf007/action-wechat-work@master
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{secrets.WECHAT_WORK_BOT_WEBHOOK}}
        with:
          msgtype: news
          articles: '[{"title":"Github Code Linter","description":"\n\n${{github.event.pull_request.user.login}} 代码检查失败","url":"https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}","picurl":"https://images.unsplash.com/photo-1623018035782-b269248df916?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"}]'


